### ISSUE TITLE
Sprint 5: Sign-off [Pending]

### ISSUE THREAD

**Issue by milaroisin** [milaroisin/xena-camera-390#19]

**Comment by ChengmingHu** [comment]
Sprint 5 is completed and the feature/planning for next sprint has been accepted.

1. Geotagging feature is well implemented.
2. The testing part will be finished in the next release. It's important.
3. Please try to implement  firebase APM in the next release.
4. Also, please don't forget the CI job log analysis in the next release
5. Just try your best to develop another feature QR Scanner. It's much better if it works. Move forward and good luck!

The account @ggebran only has two commits and three lines of code, and it is not an balanced share of work regarding coding. So please have more contribution on the project. The rest of the team shows relatively equal amounts of work.
